/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConfiguradorPC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Usuario
 */
public class VentanaHijo1 extends javax.swing.JInternalFrame {
    String ram;
    /**
     * Creates new form VentanaHijo1
     */
    public VentanaHijo1() {
        initComponents();
        show_laptop();
        jTable_Display_LaptopDetails.setDefaultEditor(Object.class, null);
    }
    public ArrayList<Laptop> listaLaptops(){
        ArrayList<Laptop> listasLaptops = new ArrayList<>();
        // parametros de la conexion
        String usr = "sa";
        String pwd = "YH6YDhmU6!X7XT";
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost\\SQLEXPRESS:56788;databaseName=JavaJ3;user=sa;password=YH6YDhmU6!X7XT";
        Connection con = null;
        //PreparedStatement pstm = null;
        //ResultSet rs = null;
        try
        {
        // -------------
        // ** PARTE 1 **
        // -------------
        // levanto el driver
        //Class.forName(driver);
        // establezco la conexion
        con = DriverManager.getConnection(url,usr,pwd);
        String query1 ="SELECT * FROM LaptopDetails";
        Statement st= con.createStatement();
        ResultSet rs= st.executeQuery(query1);
        Laptop laptop;
        while(rs.next()){
            laptop=new Laptop(rs.getInt("laptopID"), rs.getDouble("price"), rs.getString("name"), rs.getString("gpu"), rs.getString("storage"), rs.getString("cpu"), rs.getString("memory"), rs.getString("resolution"), rs.getString("screen_size"));
            listasLaptops.add(laptop);
            
        }
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex);
        }
        return listasLaptops;
    }
    
    public void show_laptop(){
        ArrayList<Laptop> list = listaLaptops();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_LaptopDetails.getModel();
        Object[] row = new Object[9];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getlaptopID();
            row[1]=list.get(i).getname();
            row[2]=list.get(i).getgpu();
            row[3]=list.get(i).getstorage();
            row[4]=list.get(i).getcpu();
            row[5]=list.get(i).getmemory();
            row[6]=list.get(i).getresolution();
            row[7]=list.get(i).getscreen_size();
            row[8]=list.get(i).getprice();
            
            model.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGpu = new javax.swing.JTextField();
        txtStorage = new javax.swing.JTextField();
        txtCpu = new javax.swing.JTextField();
        cboResolution = new javax.swing.JComboBox<>();
        rb4GB = new javax.swing.JRadioButton();
        rb8GB = new javax.swing.JRadioButton();
        rb16GB = new javax.swing.JRadioButton();
        rb32GB = new javax.swing.JRadioButton();
        rb64GB = new javax.swing.JRadioButton();
        rb128GB = new javax.swing.JRadioButton();
        txtScreenSize = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_LaptopDetails = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laptops");
        setVisible(true);

        jLabel1.setText("Nombre(Marca)");

        jLabel2.setText("Tarjeta de Video(GPU)");

        jLabel3.setText("Almacenamiento");

        jLabel4.setText("Cpu");

        jLabel5.setText("Memoria RAM");

        jLabel6.setText("Resolucion pantalla");

        jLabel7.setText("Tamaño pantalla(pulgadas)");

        jLabel8.setText("Precio(USD)");

        cboResolution.setEditable(true);
        cboResolution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1366x768", "1920x1080", "2048x1080", "2560x1440", "2560x1600", "2880x1800", "3840x2160", "4096x2160", "7680x4320" }));
        cboResolution.setSelectedIndex(1);

        buttonGroup1.add(rb4GB);
        rb4GB.setText("4GB");
        rb4GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4GBActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb8GB);
        rb8GB.setText("8GB");

        buttonGroup1.add(rb16GB);
        rb16GB.setText("16GB");

        buttonGroup1.add(rb32GB);
        rb32GB.setText("32GB");

        buttonGroup1.add(rb64GB);
        rb64GB.setText("64GB");

        buttonGroup1.add(rb128GB);
        rb128GB.setText("128GB");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Registro");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGpu)
                            .addComponent(txtStorage)
                            .addComponent(txtCpu)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb4GB)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb32GB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb8GB)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb64GB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb16GB)
                                        .addGap(12, 12, 12)
                                        .addComponent(rb128GB)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtScreenSize))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(cboResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb4GB)
                    .addComponent(rb32GB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb8GB)
                    .addComponent(rb64GB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb16GB)
                    .addComponent(rb128GB))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtScreenSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTable_Display_LaptopDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Gpu", "Almacenamiento", "cpu", "memoria ram", "resolucion", "tamaño_pantalla", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Display_LaptopDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_Display_LaptopDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_LaptopDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_LaptopDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb4GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4GBActionPerformed
        
    }//GEN-LAST:event_rb4GBActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // parametros de la conexion
        String usr = "sa";
        String pwd = "YH6YDhmU6!X7XT";
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost\\SQLEXPRESS:56788;databaseName=JavaJ3;user=sa;password=YH6YDhmU6!X7XT";
        Connection con = null;
        //PreparedStatement pstm = null;
        //ResultSet rs = null;
        try
        {
        // -------------
        // ** PARTE 1 **
        // -------------
        // levanto el driver
        //Class.forName(driver);
        // establezco la conexion
        con = DriverManager.getConnection(url,usr,pwd);
        String query ="INSERT INTO LaptopDetails(name,gpu,storage,cpu,memory,resolution,screen_size,price)values(?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1,txtName.getText());
        pst.setString(2,txtGpu.getText());
        pst.setString(3, txtStorage.getText());
        pst.setString(4,txtCpu.getText());
        if(rb4GB.isSelected()){
            ram="4 GB";
        }
        if(rb8GB.isSelected()){
            ram="8 GB";
        }
        if(rb16GB.isSelected()){
            ram="16 GB";
        }
        if(rb32GB.isSelected()){
            ram="32 GB";
        }
        if(rb64GB.isSelected()){
            ram="64 GB";
        }
        if(rb128GB.isSelected()){
            ram="128 GB";
        }
        pst.setString(5, ram);
        String resol;
        resol=cboResolution.getSelectedItem().toString();
        pst.setString(6, resol);
        pst.setString(7, txtScreenSize.getText());
        double price = Double.parseDouble(txtPrice.getText());
        pst.setDouble(8,price);
        pst.executeUpdate();
        DefaultTableModel model =(DefaultTableModel)jTable_Display_LaptopDetails.getModel();
        model.setRowCount(0);
        show_laptop();
        JOptionPane.showMessageDialog(null, "Agregado exitosamente");
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtGpu.setText("");
        txtStorage.setText("");
        txtCpu.setText("");
        buttonGroup1.clearSelection();
        cboResolution.setSelectedIndex(0);
        txtScreenSize.setText("");
        txtPrice.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        // parametros de la conexion
        String usr = "sa";
        String pwd = "YH6YDhmU6!X7XT";
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost\\SQLEXPRESS:56788;databaseName=JavaJ3;user=sa;password=YH6YDhmU6!X7XT";
        Connection con = null;
        //PreparedStatement pstm = null;
        //ResultSet rs = null;
        try
        {
        
        // establezco la conexion
        con = DriverManager.getConnection(url,usr,pwd);
        int row = jTable_Display_LaptopDetails.getSelectedRow();
        String value = (jTable_Display_LaptopDetails.getModel().getValueAt(row,0).toString());
        String query ="UPDATE LaptopDetails SET name=?, gpu=?, storage=?, cpu=?, memory=?, resolution=?, screen_size=?, price=? where laptopID="+value;
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1,txtName.getText());
        pst.setString(2,txtGpu.getText());
        pst.setString(3, txtStorage.getText());
        pst.setString(4,txtCpu.getText());
        if(rb4GB.isSelected()){
            ram="4 GB";
        }
        if(rb8GB.isSelected()){
            ram="8 GB";
        }
        if(rb16GB.isSelected()){
            ram="16 GB";
        }
        if(rb32GB.isSelected()){
            ram="32 GB";
        }
        if(rb64GB.isSelected()){
            ram="64 GB";
        }
        if(rb128GB.isSelected()){
            ram="128 GB";
        }
        pst.setString(5, ram);
        String resol;
        resol=cboResolution.getSelectedItem().toString();
        pst.setString(6, resol);
        pst.setString(7, txtScreenSize.getText());
        double price = Double.parseDouble(txtPrice.getText());
        pst.setDouble(8,price);
        pst.executeUpdate();
        DefaultTableModel model =(DefaultTableModel)jTable_Display_LaptopDetails.getModel();
        model.setRowCount(0);
        show_laptop();
        JOptionPane.showMessageDialog(null, "Modificado exitosamente");
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTable_Display_LaptopDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_LaptopDetailsMouseClicked
        // TODO add your handling code here:
        int i =jTable_Display_LaptopDetails.getSelectedRow();
        TableModel model = jTable_Display_LaptopDetails.getModel();
        txtName.setText(model.getValueAt(i, 1).toString());
        txtGpu.setText(model.getValueAt(i, 2).toString());
        txtStorage.setText(model.getValueAt(i, 3).toString());
        txtCpu.setText(model.getValueAt(i, 4).toString());
        String ram = model.getValueAt(i, 5).toString();
        if(ram.equals("4 GB")){
            rb4GB.setSelected(true);
        }
        else if(ram.equals("8 GB")){
            rb8GB.setSelected(true);
        }
        else if(ram.equals("16 GB")){
            rb16GB.setSelected(true);
        }
        else if(ram.equals("32 GB")){
            rb32GB.setSelected(true);
        }
        else if(ram.equals("64 GB")){
            rb64GB.setSelected(true);
        }
        else if(ram.equals("128 GB")){
            rb128GB.setSelected(true);
        }
        String resol=model.getValueAt(i, 6).toString();
        cboResolution.setSelectedItem(resol);
        txtScreenSize.setText(model.getValueAt(i,7).toString());
        txtPrice.setText(model.getValueAt(i,8).toString());
    }//GEN-LAST:event_jTable_Display_LaptopDetailsMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here
        // parametros de la conexion
        String usr = "sa";
        String pwd = "YH6YDhmU6!X7XT";
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url = "jdbc:sqlserver://localhost\\SQLEXPRESS:56788;databaseName=JavaJ3;user=sa;password=YH6YDhmU6!X7XT";
        Connection con = null;
        //PreparedStatement pstm = null;
        //ResultSet rs = null;
        int opt= JOptionPane.showConfirmDialog(null, "Esta seguro que desea Eliminar el registro seleccionado?","Eliminar",JOptionPane.YES_NO_OPTION);
        if(opt==0){
        try
        {
        
        // establezco la conexion
        con = DriverManager.getConnection(url,usr,pwd);
        int row = jTable_Display_LaptopDetails.getSelectedRow();
        String value = (jTable_Display_LaptopDetails.getModel().getValueAt(row,0).toString());
        String query = "DELETE FROM LaptopDetails where laptopID="+value;
        PreparedStatement pst= con.prepareStatement(query);
        pst.executeUpdate();
        DefaultTableModel model =(DefaultTableModel)jTable_Display_LaptopDetails.getModel();
        model.setRowCount(0);
        show_laptop();
        JOptionPane.showMessageDialog(null, "Eliminado exitosamente");
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboResolution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_LaptopDetails;
    private javax.swing.JRadioButton rb128GB;
    private javax.swing.JRadioButton rb16GB;
    private javax.swing.JRadioButton rb32GB;
    private javax.swing.JRadioButton rb4GB;
    private javax.swing.JRadioButton rb64GB;
    private javax.swing.JRadioButton rb8GB;
    private javax.swing.JTextField txtCpu;
    private javax.swing.JTextField txtGpu;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtScreenSize;
    private javax.swing.JTextField txtStorage;
    // End of variables declaration//GEN-END:variables
}
